[tasks]
browse = "firefox http://127.0.0.1:23461/"

[tasks.golem]
env = { GOLEM_CONFIG_ACTIVE = "dev" }
run = """
Rscript deploy/authen.R
Rscript -e 'golem::run_dev()'
"""

[tasks.r_build]
run = """
#!/usr/bin/env Rscript
tarball <- devtools::build(path = 'deploy')
file.rename(tarball, 'deploy/app.tar.gz')
renv::snapshot(exclude = c('StemDataExplorer', 'covrpage'),
               lockfile = 'deploy/renv.lock.prod',
               update = TRUE)
"""
outputs = ["deploy/renv.lock.prod", "deploy/app.tar.gz"]

[tasks.get_docker_file]
shell = "Rscript -e"
run = '''
golem::add_dockerfile_with_renv(open = FALSE, output_dir = "deploy")
'''
sources = ["R/*"]
outputs = [
  "deploy/Dockerfile",
  "deploy/renv.lock.prod",
  "deploy/Dockerfile_base",
]

[tasks.docker_build]
description = "Build docker image"
depends = ["get_docker_file"]
dir = "./deploy"
run = '''
docker build -f fixed.dockerfile -t stemdataexplorer:latest .
'''

[tasks.docker_run]
run = '''
docker kill $(docker ps -q) || echo "No running images"
docker run \
       -e GOLEM_CONFIG_FILE=/home/stem/config.yml \
       --mount type=bind,src=$(pwd)/inst/golem-config.yml,dst=/home/stem/config.yml \
       --mount type=bind,src=$(pwd)/app_cache/cache,dst=/home/stem/app_cache \
       -p 80:80 \
       stemdataexplorer:latest
'''
# NOTE: [2026-05-25 Mon] switched to using apptainer because intended
# server doesn't support docker

[tasks.clean]
run = '''
if [[ -e "deploy" ]]; then
   rm deploy/image.sif
   rm deploy/renv.lock.prod
   rm deploy/Dockerfile
   rm deploy/StemDataExplorer*.tar.gz
   rm deploy/Dockerfile_base
fi
'''

[tasks.apptainer_run]
env = { GOLEM_CONFIG_ACTIVE = "dev" }
run = '''
sudo apptainer instance run \
          --env GOLEM_CONFIG_FILE=./inst/golem-config.yml \
          --env GOLEM_CONFIG_ACTIVE=dev \
          --network-args "portmap=80:80/tcp" \
          ./deploy/image.sif shiny
'''

[tasks.apptainer_exec]
run = '''
apptainer exec  \
          --env GOLEM_CONFIG_FILE=inst/golem-config.yml \
          --env GOLEM_CONFIG_ACTIVE=dev \
          ./deploy/image.sif \
          R -e "options('shiny.port'=8888,shiny.host='0.0.0.0');library(StemDataExplorer);StemDataExplorer::run_app()"
'''
# View with firefox http://0.0.0.0:8888


[tasks.set_up_dev]
usage = '''
flag "--remove" help="Remove old cache" default="false"
arg "[vals_remove]" help = "Force remove values" var=#true
'''
run = '''
if [[ "${usage_remove}" == "true" ]]; then
   Rscript inst/set_up.R -f inst/golem-config.yml -c dev -r
elif [[ -n "${usage_vals_remove}" ]]; then
   Rscript inst/set_up.R -f inst/golem-config.yml -c dev -u "${usage_vals_remove}"   
else
   Rscript inst/set_up.R -f inst/golem-config.yml -c dev
fi

'''

[tasks.apptainer_build]
dir = "./deploy"
env = { GOLEM_CONFIG_ACTIVE = "production" }
depends = ["r_build"]
sources = ["deploy/image.def"]
run = '''
export APPTAINER_TMPDIR=/home/shannc/Bio_SDD/build
Rscript authen.R 
apptainer build --force \
          -B ~/.cache/R/renv_singularity:/tmp/renv_singularity \
          image.sif image.def
'''
outputs = ["deploy/image.sif"]

[tasks.send]
usage = '''
flag "--cache" help="Send image file" default="false"
'''
run = '''
if [[ "${usage_remove}" == "true" ]]; then
   rsync -r app_cache $stem_ip:~/remote/repos/StemDataExplorer/image.sif
else
   rsync deploy/image.sif $stem_ip:~/remote/repos/StemDataExplorer/image.sif
fi
'''

[tasks.get_sample_sheet_nas]
run = '''
rsync stem_cell_admin@10.39.181.155:~/files.txt .
python inst/get_sample_catalog.py -i files.txt \
       -r /volume1/cancer_ngs \
       -o inst/tmp/sample_catalog.csv
rm files.txt
'''
